workspace "PracticeChallenges"
	architecture "x86_64"
	startproject "Challenge1"

	configurations
	{
		"Debug",
		"Release",
		"RelWithDebInfo"
	}

	flags
	{
		"MultiProcessorCompile"
	}

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

group "Codewars.com Fundamentals/1-50"
	include "Challenges/Codewars_Fundamentals/Challenge1"
	include "Challenges/Codewars_Fundamentals/Challenge2"
	include "Challenges/Codewars_Fundamentals/Challenge3"
	include "Challenges/Codewars_Fundamentals/Challenge4"
	include "Challenges/Codewars_Fundamentals/Challenge5"
	include "Challenges/Codewars_Fundamentals/Challenge6"
	include "Challenges/Codewars_Fundamentals/Challenge7"
	include "Challenges/Codewars_Fundamentals/Challenge8"
	include "Challenges/Codewars_Fundamentals/Challenge9"
	include "Challenges/Codewars_Fundamentals/Challenge10"
	include "Challenges/Codewars_Fundamentals/Challenge11"
	include "Challenges/Codewars_Fundamentals/Challenge12"
	include "Challenges/Codewars_Fundamentals/Challenge13"
	include "Challenges/Codewars_Fundamentals/Challenge14"
	include "Challenges/Codewars_Fundamentals/Challenge15"
	include "Challenges/Codewars_Fundamentals/Challenge16"
	include "Challenges/Codewars_Fundamentals/Challenge17"
	include "Challenges/Codewars_Fundamentals/Challenge18"
	include "Challenges/Codewars_Fundamentals/Challenge19"
	include "Challenges/Codewars_Fundamentals/Challenge20"
	include "Challenges/Codewars_Fundamentals/Challenge21"
	include "Challenges/Codewars_Fundamentals/Challenge22"
	include "Challenges/Codewars_Fundamentals/Challenge23"
	include "Challenges/Codewars_Fundamentals/Challenge24"
	include "Challenges/Codewars_Fundamentals/Challenge25"
	include "Challenges/Codewars_Fundamentals/Challenge26"
	include "Challenges/Codewars_Fundamentals/Challenge27"
	include "Challenges/Codewars_Fundamentals/Challenge28"
	include "Challenges/Codewars_Fundamentals/Challenge29"
	include "Challenges/Codewars_Fundamentals/Challenge30"
	include "Challenges/Codewars_Fundamentals/Challenge31"
	include "Challenges/Codewars_Fundamentals/Challenge32"
	include "Challenges/Codewars_Fundamentals/Challenge33"
	include "Challenges/Codewars_Fundamentals/Challenge34"
	include "Challenges/Codewars_Fundamentals/Challenge35"
	include "Challenges/Codewars_Fundamentals/Challenge36"
	include "Challenges/Codewars_Fundamentals/Challenge37"
	include "Challenges/Codewars_Fundamentals/Challenge38"
	include "Challenges/Codewars_Fundamentals/Challenge39"
	include "Challenges/Codewars_Fundamentals/Challenge40"
	include "Challenges/Codewars_Fundamentals/Challenge41"
	include "Challenges/Codewars_Fundamentals/Challenge42"
	include "Challenges/Codewars_Fundamentals/Challenge43"
	include "Challenges/Codewars_Fundamentals/Challenge44"
	include "Challenges/Codewars_Fundamentals/Challenge45"
	include "Challenges/Codewars_Fundamentals/Challenge46"
	include "Challenges/Codewars_Fundamentals/Challenge47"
	include "Challenges/Codewars_Fundamentals/Challenge48"
	include "Challenges/Codewars_Fundamentals/Challenge49"
	include "Challenges/Codewars_Fundamentals/Challenge50"

group "Codewars.com Fundamentals/51-100"
	include "Challenges/Codewars_Fundamentals/Challenge51"
	include "Challenges/Codewars_Fundamentals/Challenge52"
	include "Challenges/Codewars_Fundamentals/Challenge53"
	include "Challenges/Codewars_Fundamentals/Challenge54"
	include "Challenges/Codewars_Fundamentals/Challenge55"
	include "Challenges/Codewars_Fundamentals/Challenge56"
	include "Challenges/Codewars_Fundamentals/Challenge57"
	include "Challenges/Codewars_Fundamentals/Challenge58"
	include "Challenges/Codewars_Fundamentals/Challenge59"
	include "Challenges/Codewars_Fundamentals/Challenge60"
	include "Challenges/Codewars_Fundamentals/Challenge61"
	include "Challenges/Codewars_Fundamentals/Challenge62"
	include "Challenges/Codewars_Fundamentals/Challenge63"
	include "Challenges/Codewars_Fundamentals/Challenge64"
	include "Challenges/Codewars_Fundamentals/Challenge65"
	include "Challenges/Codewars_Fundamentals/Challenge66"
	include "Challenges/Codewars_Fundamentals/Challenge67"
	include "Challenges/Codewars_Fundamentals/Challenge68"
	include "Challenges/Codewars_Fundamentals/Challenge69"
	include "Challenges/Codewars_Fundamentals/Challenge70"
	include "Challenges/Codewars_Fundamentals/Challenge71"
	include "Challenges/Codewars_Fundamentals/Challenge72"
	include "Challenges/Codewars_Fundamentals/Challenge73"
	include "Challenges/Codewars_Fundamentals/Challenge74"
	include "Challenges/Codewars_Fundamentals/Challenge75"
	include "Challenges/Codewars_Fundamentals/Challenge76"
	include "Challenges/Codewars_Fundamentals/Challenge77"
	include "Challenges/Codewars_Fundamentals/Challenge78"
	include "Challenges/Codewars_Fundamentals/Challenge79"
	include "Challenges/Codewars_Fundamentals/Challenge80"
	include "Challenges/Codewars_Fundamentals/Challenge81"
	include "Challenges/Codewars_Fundamentals/Challenge82"
	include "Challenges/Codewars_Fundamentals/Challenge83"
	include "Challenges/Codewars_Fundamentals/Challenge84"
	include "Challenges/Codewars_Fundamentals/Challenge85"
	include "Challenges/Codewars_Fundamentals/Challenge86"
	include "Challenges/Codewars_Fundamentals/Challenge87"
	include "Challenges/Codewars_Fundamentals/Challenge88"
	include "Challenges/Codewars_Fundamentals/Challenge89"
	include "Challenges/Codewars_Fundamentals/Challenge90"
	include "Challenges/Codewars_Fundamentals/Challenge91"
	include "Challenges/Codewars_Fundamentals/Challenge92"
	include "Challenges/Codewars_Fundamentals/Challenge93"
	include "Challenges/Codewars_Fundamentals/Challenge94"
	include "Challenges/Codewars_Fundamentals/Challenge95"
	include "Challenges/Codewars_Fundamentals/Challenge96"
	include "Challenges/Codewars_Fundamentals/Challenge97"
	include "Challenges/Codewars_Fundamentals/Challenge98"
	include "Challenges/Codewars_Fundamentals/Challenge99"
	include "Challenges/Codewars_Fundamentals/Challenge100"

group "Codewars.com Fundamentals/101-150"
	include "Challenges/Codewars_Fundamentals/Challenge101"
	include "Challenges/Codewars_Fundamentals/Challenge102"
	include "Challenges/Codewars_Fundamentals/Challenge103"
	include "Challenges/Codewars_Fundamentals/Challenge104"
	include "Challenges/Codewars_Fundamentals/Challenge105"
	include "Challenges/Codewars_Fundamentals/Challenge106"
	include "Challenges/Codewars_Fundamentals/Challenge107"
	include "Challenges/Codewars_Fundamentals/Challenge108"
	include "Challenges/Codewars_Fundamentals/Challenge109"
	include "Challenges/Codewars_Fundamentals/Challenge110"
	include "Challenges/Codewars_Fundamentals/Challenge111"